# Generated by Django 3.2.6 on 2021-08-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blg',
            name='price',
        ),
        migrations.AddField(
            model_name='blg',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
